# Header
menu:
  Home: /
  Archives: /archives
  Profile: /profile
  Twitter: https://twitter.com/kume_negitoro
  Github: https://github.com/kume-negitoro
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /favicon.png